import = ["~/.config/alacritty/themes/themes/citylights.toml"]

[cursor]
style = { shape = "Block", blinking = "On" }
thickness = 0.2

[font]
bold = { style = "Bold", family = "BlexMono Nerd Font" }
bold_italic = { style = "Bold Italic", family = "BlexMono Nerd Font" }
italic = { style = "Italic", family = "BlexMono Nerd Font" }
normal = { style = "Medium", family = "BlexMono Nerd Font" }
offset = { x = 0, y = 5 }
size = 13.0

[selection]
save_to_clipboard = true

[window]
blur = true
dimensions = { columns = 110, lines = 23 }
dynamic_padding = true
opacity = 0.97
padding = { x = 7, y = 7 }
startup_mode = "Windowed"
