import = ["~/.config/alacritty/themes/themes/rose-pine.toml"]

[cursor]
style = { shape = "Block", blinking = "On" }
thickness = 0.2

[font]
bold = { style = "Bold", family = "Monocode" }
bold_italic = { style = "Bold Italic", family = "Monocode" }
italic = { style = "Italic", family = "Monocode" }
normal = { style = "Medium", family = "Monocode" }
offset = { x = 0, y = 2 }
size = 14

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[selection]
save_to_clipboard = true

[window]
blur = true
dimensions = { columns = 117, lines = 27 }
dynamic_padding = true
opacity = 0.95
padding = { x = 3, y = 3 }
startup_mode = "Windowed"
decorations = "none"
