import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

[font]
size = 11.0

[font.normal]
family = "MartianMono Nerd Font"

[font.bold]
family = "MartianMono Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 7
y = 7

[cursor]
style = { shape = "Block", blinking = "On" }