import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[cursor]
style = { shape = "Block", blinking = "On" }
thickness = 0.2

[font]
bold = { style = "Bold", family = "JetbrainsMono Nerd Font" }
bold_italic = { style = "Bold Italic", family = "JetbrainsMono Nerd Font" }
italic = { style = "Italic", family = "JetbrainsMono Nerd Font" }
normal = { style = "Medium", family = "JetbrainsMono Nerd Font" }
offset = { x = 0, y = 0 }
size = 14

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[selection]
save_to_clipboard = true

[window]
blur = true
dimensions = { columns = 110, lines = 23 }
dynamic_padding = true
opacity = 0.95
padding = { x = 7, y = 7 }
startup_mode = "Windowed"
