import = ["~/.config/alacritty/themes/themes/citylights.toml"]

[cursor]
style = { shape = "Block", blinking = "On" }
thickness = 0.2

[font]
bold = { style = "Bold", family = "MartianMono Nerd Font" }
bold_italic = { style = "Bold Italic", family = "MartianMono Nerd Font" }
italic = { style = "Italic", family = "MartianMono Nerd Font" }
normal = { style = "Medium", family = "MartianMono Nerd Font" }
offset = { x = -1, y = 3 }
size = 11.0

[selection]
save_to_clipboard = true

[window]
blur = true
dimensions = { columns = 110, lines = 27 }
dynamic_padding = true
opacity = 0.97
padding = { x = 7, y = 7 }
startup_mode = "Windowed"
